package lab2;

//Generated by Selenium IDE
import java.io.FileInputStream;
import java.io.InputStream;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Lab2 {
	public void getValues(String filePath ) 
    {
        //String values = null;
        try{
            InputStream is = new FileInputStream(filePath);
            // 构造 XSSFWorkbook 对象，strPath 传入文件路径  
            XSSFWorkbook xwb = new XSSFWorkbook(is);  
            // 读取第一个表格内容  
            XSSFSheet sheet = xwb.getSheetAt(0);  
            // 定义 row、cell  
            XSSFRow row;  
            String name;
            String password;
            
          //1. 定义FireFox浏览器驱动
    		String driverPath = System.getProperty("user.dir") + "/src/resources/driver/geckodriver.exe";
    		System.setProperty("webdriver.gecko.driver", driverPath);
    		System.setProperty("webdriver.firefox.bin", "F://firebox/firefox.exe");
    		WebDriver driver = new FirefoxDriver();
    		
    		 //二、定义要访问的网址
            String baseUrl = "http://103.120.226.190/selenium-demo/git-repo";
            String actual = "";
            
          //三、访问给定的网址launch Fire fox and direct it to the Base URL
            driver.get(baseUrl);
            
//sheet.getPhysicalNumberOfRows()
            // 循环输出表格中的内容  
            for (int i = sheet.getFirstRowNum(); i < 20; i++) {  
                row = sheet.getRow(i);                 	
                    // 通过 row.getCell(j).toString() 获取单元格内容，  
                    name = row.getCell(1).toString();
                    password = row.getCell(2).toString();
                    
                    

                    //四、actual
                    WebElement userName = driver.findElement(By.name("user_number"));
            		userName.sendKeys(name);
            		WebElement passName = driver.findElement(By.name("password"));
            		passName.sendKeys(password);
            		WebElement submitName = driver.findElement(By.xpath("/html/body/div/div/div/div/div/div/div[2]/div/form/div[3]/input"));
            		submitName.click();
            		WebElement textShow = driver.findElement(By.xpath("/html/body/div/div/div/div/div/div/div[2]/div/form/div[5]/code"));
            		
            		// System.out.println(textShow.getText())       ;                                      
                    /*
                     * 五、比对Title和预期值compare the actual title of the page with the expected one and print
                     * the result as "Passed" or "Failed"
                     */
            		//System.out.println(password);
            		
                    if (textShow.getText().equals(password)){
                        System.out.println("Test Passed!");
                    } else {
                        System.out.println("Test Failed");
                    }
                   
                   // close Fire fox
                   // driver.close();
            			
           } 
            }catch(Exception e) {
                System.out.println("已运行xlRead() : " + e );
            }
    }
	
	
	
	public static void main(String args[]) 
    {
       String filePath="C:\\软件测试\\Selenium+Lab2020.xlsx";
     
        checkRecord er = new checkRecord();
         er.getValues(filePath);
    }

}
